In [18]:
# Operación suma

# Operación flotante

# Operaciones con string

# Comparaciones


# Operadores en Python

| Operador      | Descripción                                             | Ejemplo                       |
| ------------- | ------------------------------------------------------- | ----------------------------- |
| `==`          | Igual a: Compara si dos valores son iguales             | `5 == 5` (True)               |
| `!=`          | No igual a: Compara si dos valores no son iguales       | `5 != 3` (True)               |
| `>`           | Mayor que: Compara si el valor de la izquierda es mayor | `5 > 3` (True)                |
| `<`           | Menor que: Compara si el valor de la izquierda es menor | `5 < 3` (False)               |
| `>=`          | Mayor o igual que                                        | `5 >= 3` (True)               |
| `<=`          | Menor o igual que                                        | `5 <= 5` (True)               |
| `and`         | Operador lógico AND: Devuelve True si ambos son True     | `True and False` (False)      |
| `or`          | Operador lógico OR: Devuelve True si al menos uno es True| `True or False` (True)        |
| `not`         | Operador lógico NOT: Invierte el valor lógico            | `not True` (False)            |
| `is`          | Operador de identidad: Compara si dos objetos son el mismo| `x is y`                      |
| `in`          | Operador de pertenencia: Comprueba si un valor está en una secuencia | `'a' in 'abc'` (True)  |


In [19]:
x = 12
y = 8
x is y

False

In [20]:
# Ejemplos de python
0.3 == 0.1+0.1+0.1

False

In [21]:
None > 0

TypeError: '>' not supported between instances of 'NoneType' and 'int'

In [22]:
import math 

math.nan == math.nan

False

In [23]:
-0.0 == 0.0

True

In [24]:
"10"==10

False

In [25]:
[] == None

False

In [26]:
[] is None

False




| A     | B     | A and B | A or B  |
| ----- | ----- | ------- | ------- |
| True  | True  | True    | True    |
| True  | False | False   | True    |
| False | True  | False   | True    |
| False | False | False   | False   |


In [27]:
x = True 
y = not True

In [28]:
0 and 0

0

# Secuencias

##  Arreglos

In [30]:
from datascience import *
make_array(1, 2,2, 3, )

array([1, 2, 2, 3])

In [31]:
# Multiplicación, división 

In [32]:
type(make_array(1, 2,2, 3, ))

numpy.ndarray

In [34]:
temperatura = make_array(23, 25, 26, 28, )

Pasemos los valores de temperatura a kelvin

In [36]:
temperatura + 273 

array([296, 298, 299, 301])

In [38]:
q = make_array("hola", "mundo")
q

array(['hola', 'mundo'],
      dtype='<U5')

## Funciones sobre arreglos

Tomado de [data 8 book](https://inferentialthinking.com/chapters/05/1/Arrays.html)

## Tabla 1: Funciones de agregación

| Función           | Descripción                                                     |
|-------------------|-----------------------------------------------------------------|
| `np.prod`         | Multiplica todos los elementos                                  |
| `np.sum`          | Suma todos los elementos                                        |
| `np.all`          | Verifica si todos los elementos son verdaderos (números diferentes de 0 son verdaderos) |
| `np.any`          | Verifica si alguno de los elementos es verdadero (números diferentes de 0 son verdaderos) |
| `np.count_nonzero`| Cuenta el número de elementos diferentes de cero                |



## Tabla 2: Funciones de transformación numérica

| Función           | Descripción                                                     |
|-------------------|-----------------------------------------------------------------|
| `np.diff`         | Diferencia entre elementos adyacentes                            |
| `np.round`        | Redondea cada número al entero más cercano                       |
| `np.cumprod`      | Producto acumulado: para cada elemento, multiplica todos los elementos hasta ese punto |
| `np.cumsum`       | Suma acumulada: para cada elemento, suma todos los elementos hasta ese punto |
| `np.exp`          | Eleva cada elemento a la exponencial                             |
| `np.log`          | Aplica el logaritmo natural a cada elemento                      |
| `np.sqrt`         | Calcula la raíz cuadrada de cada elemento                        |
| `np.sort`         | Ordena los elementos                                             |


## Tabla 3: Funciones para manipulación de strings

| Función            | Descripción                                                    |
|--------------------|----------------------------------------------------------------|
| `np.char.lower`     | Convierte cada elemento a minúsculas                           |
| `np.char.upper`     | Convierte cada elemento a mayúsculas                           |
| `np.char.strip`     | Elimina espacios al principio o al final de cada elemento      |
| `np.char.isalpha`   | Verifica si cada elemento contiene solo letras (sin números ni símbolos) |
| `np.char.isnumeric` | Verifica si cada elemento contiene solo números (sin letras)   |



## Tabla 4: Funciones de búsqueda en strings

| Función             | Descripción                                                  |
|---------------------|--------------------------------------------------------------|
| `np.char.count`      | Cuenta cuántas veces aparece una cadena de búsqueda en los elementos del arreglo |
| `np.char.find`       | Devuelve la posición en la que se encuentra la cadena de búsqueda por primera vez en cada elemento |
| `np.char.rfind`      | Devuelve la posición en la que se encuentra la cadena de búsqueda por última vez en cada elemento |
| `np.char.startswith` | Verifica si cada elemento comienza con la cadena de búsqueda |


In [39]:
import numpy as np

In [40]:
make_array(...)

array([Ellipsis], dtype=object)

In [43]:
q=make_array("por la", "libertad")
np.char.upper(q)

array(['POR LA', 'LIBERTAD'],
      dtype='<U8')

# Aumento de la presión con la profundidad

Al bucear, la presión experimentada aumenta a medida que se incrementa la profundidad. Este aumento de presión puede modelarse con la siguiente ecuación:

\begin{equation}
P = P_0 + \rho g h
\end{equation}

Donde:
- $P$ es la presión total a una determinada profundidad.
- $P_0$ es la presión atmosférica a nivel del mar: 1atm es 101.325 pascales (Pa)
- $\rho$ es la densidad del agua (aproximadamente 1000 kg/m³ para agua dulce).
- $g$ es la aceleración gravitacional (aproximadamente 9.81 m/s²).
- $h$ es la profundidad en metros.

Calcular la presión en atmósferas para las siguientes profundidades:

```
h = 0, 10, 20, 30, 40, 50 m
```

Determinar el aumento diferencial de presión, es decir hacer el cálculo de la diferencia entre el primer y segundo valor, entre el tercero y segundo y asi sucesivamente: emplea `np.diff`


In [46]:
h = make_array(0, 10, 20, 30, 40, 50)
np.diff(h)

array([10, 10, 10, 10, 10])

In [47]:
notas = make_array(2.5, 4.5, 5.0)
promedio = np.sum(notas)/len(notas)
promedio

4.0

In [48]:
promedio = np.mean(notas)
promedio

4.0

# Rangos

Enfatizar en la diferencia entre diferentes tipos de datos y los rangos

In [49]:
u = np.arange(5)
u

array([0, 1, 2, 3, 4])

In [50]:
u.take(2)

2

## Leibniz's Formula for Pi

La fórmula de Leibniz para calcular $\pi$ es una serie infinita alternada que converge hacia $\pi$ cuando se multiplica por 4. Se puede expresar de la siguiente manera:

\begin{equation}
\frac{\pi}{4} = 1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \cdots
\end{equation}

También se puede reorganizar la fórmula separando los términos positivos y negativos en dos series distintas:

\begin{equation}
\frac{\pi}{4} = \left( 1 + \frac{1}{5} + \frac{1}{9} + \cdots \right) - \left( \frac{1}{3} + \frac{1}{7} + \frac{1}{11} + \cdots \right)
\end{equation}

Esta fórmula es una representación elegante de $\pi$,  aunque su convergencia es relativamente lenta.

¿Calcular el valor de pi?

In [52]:
tabla_periodica = Table().with_columns( ["temperatura", ["Si", "K", "Fe", "Co"], "NumeroAtomico", [14,19,26,27] ])
tabla_periodica.take(range(1, 2))

temperatura | NumeroAtomico
K           | 19

In [54]:
tabla_periodica.select("NumeroAtomico")

NumeroAtomico
14
19
26
27

In [55]:
tabla_periodica.column("NumeroAtomico")

array([14, 19, 26, 27])

#  Repaso de tablas

| **Método**                                  | **Descripción**                                                                 |
|---------------------------------------------|---------------------------------------------------------------------------------|
| `Table.read_table(file_path)`               | Lee un archivo CSV y devuelve una tabla.                                        |
| `table.show(n)`                             | Muestra las primeras `n` filas de la tabla.                                     |
| `table.with_columns(column1, values1, ...)` | Agrega una o más columnas nuevas a la tabla.                                    |
| `table.column(column_name)`                 | Devuelve los valores de una columna como un array de Numpy.                     |
| `table.num_columns()`                       | Devuelve el número de columnas en la tabla.                                     |
| `table.num_rows()`                          | Devuelve el número de filas en la tabla.                                        |
| `table.select(column_name1, column_name2)`  | Selecciona y devuelve una tabla con solo las columnas indicadas.                |
| `table.drop(column_name1, column_name2)`    | Elimina las columnas especificadas y devuelve una tabla nueva.                  |
| `table.where(column_name, predicate)`       | Filtra las filas según una condición en una columna específica.                 |
| `table.sort(column_name, descending=False)` | Ordena la tabla por una columna en orden ascendente o descendente.              |


## Creacion de una tabla 
Supongamos que queremos construir una tabla con las distancia al sol,  y la masa de cada planeta.

| Planeta    | Distancia al Sol (UA) | Masa (Unidades de masas terrestres) |
|------------|-----------------------|-------------------------------------|
| Mercurio   | 0.39                  | 0.055                              |
| Venus      | 0.72                  | 0.815                              |
| Tierra     | 1.00                  | 1.000                              |
| Marte      | 1.52                  | 0.107                              |
| Júpiter    | 5.20                  | 317.8                              |
| Saturno    | 9.58                  | 95.2                               |
| Urano      | 19.22                 | 14.5                               |
| Neptuno    | 30.05                 | 17.1                               |

Nota:  
- 1 UA ≈ 149.6 millones de kilómetros
- 5.97 × 10²⁴ kilogramos.

Las siguientes celdas contiene la informaciòn par no copiar todos los datos: 

```python 
distancias_ua = [0.39, 0.72, 1.00, 1.52, 5.20, 9.58, 19.22, 30.05]
```

```python 
masas_terrestres = [0.055, 0.815, 1.000, 0.107, 317.8, 95.2, 14.5, 17.1]
```

In [56]:
from  datascience import * 

In [57]:
# Construyendo la tabla
Table().with_columns(["Planeta", ["Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno"],
                      "DistanciaSol", [0.39, 0.72, 1.00, 1.52, 5.20, 9.58, 19.22, 30.05],
                      "Masa", [0.055, 0.815, 1.000, 0.107, 317.8, 95.2, 14.5, 17.1],                     
                     ])


Planeta  | DistanciaSol | Masa
Mercurio | 0.39         | 0.055
Venus    | 0.72         | 0.815
Tierra   | 1            | 1
Marte    | 1.52         | 0.107
Júpiter  | 5.2          | 317.8
Saturno  | 9.58         | 95.2
Urano    | 19.22        | 14.5
Neptuno  | 30.05        | 17.1

In [62]:
# Almacenado la tabla en una variable
planetas=Table().with_columns(["Nombre", ["Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno"],
                      "DistanciaSol", [0.39, 0.72, 1.00, 1.52, 5.20, 9.58, 19.22, 30.05],
                      "Masa", [0.39, 0.72, 1.00, 1.52, 5.20, 9.58, 19.22, 30.05],                     
                     ])
planetas

Nombre   | DistanciaSol | Masa
Mercurio | 0.39         | 0.39
Venus    | 0.72         | 0.72
Tierra   | 1            | 1
Marte    | 1.52         | 1.52
Júpiter  | 5.2          | 5.2
Saturno  | 9.58         | 9.58
Urano    | 19.22        | 19.22
Neptuno  | 30.05        | 30.05

## table.take
## table.show

In [63]:
planetas.take(0)

Nombre   | DistanciaSol | Masa
Mercurio | 0.39         | 0.39

In [64]:
planetas.select("Nombre")

Nombre
Mercurio
Venus
Tierra
Marte
Júpiter
Saturno
Urano
Neptuno

In [65]:
planetas.labels

('Nombre', 'DistanciaSol', 'Masa')

In [66]:
planetas.rows

Rows(Nombre   | DistanciaSol | Masa
Mercurio | 0.39         | 0.39
Venus    | 0.72         | 0.72
Tierra   | 1            | 1
Marte    | 1.52         | 1.52
Júpiter  | 5.2          | 5.2
Saturno  | 9.58         | 9.58
Urano    | 19.22        | 19.22
Neptuno  | 30.05        | 30.05)

In [67]:
len(planetas)

3

In [68]:
planetas.sort("Masa", descending=False)

Nombre   | DistanciaSol | Masa
Mercurio | 0.39         | 0.39
Venus    | 0.72         | 0.72
Tierra   | 1            | 1
Marte    | 1.52         | 1.52
Júpiter  | 5.2          | 5.2
Saturno  | 9.58         | 9.58
Urano    | 19.22        | 19.22
Neptuno  | 30.05        | 30.05

In [69]:
planetas.drop("Masa")

Nombre   | DistanciaSol
Mercurio | 0.39
Venus    | 0.72
Tierra   | 1
Marte    | 1.52
Júpiter  | 5.2
Saturno  | 9.58
Urano    | 19.22
Neptuno  | 30.05

# Lectura de tablas

1. Muestra los 10 primeros valores de la tabla

2. Selecciona las columnas "Animal" y "Velocidad Promedio (km/h)"

3. Determina el animal que tiene mayor peso


In [74]:
animals = Table().read_table("Animales_.csv")
animals

Unnamed: 0 | Animal                     | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
0          | Cerdo Hormiguero           | 117.5       | 52.5      | 40
1          | Lobo Terrícola             | 45          | 11        | 27
2          | Elefante Africano          | 290         | 4350      | 25
3          | León Africano              | 95          | 185       | 58
4          | Perro Salvaje Africano     | 77.5        | 27        | 56
5          | Íbice Alpino               | 84          | 69.5      | 60
6          | Rana de la Selva Amazónica | 7.5         | 0         | 0.55
7          | Bisonte Americano          | 169         | nan       | 48
8          | Oso Hormiguero             | 71.5        | 31.5      | 24
9          | Caballo Árabe              | 150         | 690       | 65
... (168 rows omitted)

In [75]:
animales = animals.drop("Unnamed: 0")
animales

Animal                     | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Cerdo Hormiguero           | 117.5       | 52.5      | 40
Lobo Terrícola             | 45          | 11        | 27
Elefante Africano          | 290         | 4350      | 25
León Africano              | 95          | 185       | 58
Perro Salvaje Africano     | 77.5        | 27        | 56
Íbice Alpino               | 84          | 69.5      | 60
Rana de la Selva Amazónica | 7.5         | 0         | 0.55
Bisonte Americano          | 169         | nan       | 48
Oso Hormiguero             | 71.5        | 31.5      | 24
Caballo Árabe              | 150         | 690       | 65
... (168 rows omitted)

# Operacion sobre tablas


## Predicados

| Predicado                     | Descripción                                                  |
| ------------------------------| ------------------------------------------------------------ |
| `are.equal_to(Z)`              | Igual a Z                                                    |
| `are.above(x)`                 | Mayor que x                                                  |
| `are.above_or_equal_to(x)`     | Mayor o igual a x                                            |
| `are.below(x)`                 | Menor que x                                                  |
| `are.below_or_equal_to(x)`     | Menor o igual a x                                            |
| `are.between(x, y)`            | Mayor o igual a x y menor que y                              |
| `are.strictly_between(x, y)`   | Mayor que x y menor que y                                    |
| `are.between_or_equal_to(x, y)`| Mayor o igual a x y menor o igual a y                        |
| `are.containing(S)`            | Contiene la cadena de texto S                                |

## Predicados Negados

Puedes especificar la negación de cualquiera de estas condiciones utilizando `.not_` antes del predicado:

| Predicado Negado               | Descripción                                                  |
| ------------------------------| ------------------------------------------------------------ |
| `are.not_equal_to(Z)`          | No igual a Z                                                 |
| `are.not_above(x)`             | No mayor que x                                               |


In [76]:
animales.where("Altura (cm)", are.above(100))

Animal                       | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Cerdo Hormiguero             | 117.5       | 52.5      | 40
Elefante Africano            | 290         | 4350      | 25
Bisonte Americano            | 169         | nan       | 48
Caballo Árabe                | 150         | 690       | 65
Arowana                      | 120         | 6         | 24
Elefante Asiático            | 250         | 3500      | 40
Delfín Moteado del Atlántico | 225         | 130       | 52
Foca de Pelo Australiana     | 136         | 29        | 32
Tiburón Peregrino            | 1100        | 550       | 21
Rinoceronte Negro            | 156         | nan       | 56
... (56 rows omitted)

In [78]:
animales.where('Velocidad Promedio (km/h)', are.equal_to(48))

Animal            | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Bisonte Americano | 169         | nan       | 48
Tapir de Baird    | 91.5        | 275       | 48
Oso Pardo         | 95          | 425       | 48
Zorro Rojo        | 42.5        | 5         | 48
Tapir             | 95          | 275       | 48

In [79]:
animales.where('Velocidad Promedio (km/h)', are.between(40,40))

Animal                | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Cerdo Hormiguero      | 117.5       | 52.5      | 40
Elefante Asiático     | 250         | 3500      | 40
Frailecillo Atlántico | 27.5        | 560       | 40
Zorro de Bengala      | 37.5        | 3.25      | 40
Ballena Azul          | 33          | 200       | 40
Chimpancé             | 160         | 48        | 40
Gorila del Este       | 164         | 138.5     | 40
Camarón Mantis        | 30          | 2         | 40
Gorila de Montaña     | 160         | 135       | 40
Oso Polar             | 160         | 700       | 40
... (5 rows omitted)

In [80]:
animales.where('Animal', are.containing('Tiburón'))

Animal                      | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Tiburón Peregrino           | 1100        | 550       | 21
Tiburón Duende              | 320         | 210       | 2.3
Tiburón Blanco              | 610         | 2268      | 56
Tiburón Blanco              | 670         | 2268      | 56
Tiburón Mako de Aleta Corta | 394         | 800       | 45
Tiburón Ballena             | 1800        | 1500      | 70
Tiburón Cebra               | 330         | 32        | 20

In [81]:
animales.sort("Velocidad Promedio (km/h)", descending = True)

Animal                   | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Águila Calva             | 86          | 4.5       | 120
Guepardo                 | 80          | 46        | 112
Berrendo                 | 92.5        | 55        | 88.5
Búho Nival               | 61.5        | 2.45      | 80
Lince Ibérico            | 65          | 11.5      | 75
Camarón Mantis Pavo Real | 18          | 0         | 72
Tiburón Ballena          | 1800        | 1500      | 70
Caballo Árabe            | 150         | 690       | 65
Tigre de Bengala         | 100         | 240       | 65
Perro Bóxer              | 58          | 28.5      | 64
... (168 rows omitted)

In [88]:
animales.select("Animal")

Animal
Cerdo Hormiguero
Lobo Terrícola
Elefante Africano
León Africano
Perro Salvaje Africano
Íbice Alpino
Rana de la Selva Amazónica
Bisonte Americano
Oso Hormiguero
Caballo Árabe
... (168 rows omitted)

In [89]:
animales.column("Animal")

array(['Cerdo Hormiguero', 'Lobo Terrícola', 'Elefante Africano',
       'León Africano', 'Perro Salvaje Africano', 'Íbice Alpino',
       'Rana de la Selva Amazónica', 'Bisonte Americano', 'Oso Hormiguero',
       'Caballo Árabe', 'Órix Árabe', 'Zorro Ártico', 'Arowana',
       'Elefante Asiático', 'Frailecillo Atlántico',
       'Delfín Moteado del Atlántico', 'Foca de Pelo Australiana',
       'Ajolote', 'Aye-Aye', 'Tapir de Baird', 'Águila Calva',
       'Civeta de Palma Banded', 'Macaco de Berbería', 'Tiburón Peregrino',
       'Dragón Barbudo', 'Zorro de Bengala', 'Tigre de Bengala',
       'Rinoceronte Negro', 'Arrendajo Azul', 'Ballena Azul',
       'Piquero de Patas Azules', 'Bonobo', 'Orangután de Borneo',
       'Delfín Nariz de Botella', 'Perro Bóxer', 'Oso Pardo',
       'Pitón Birmana', 'Capibara', 'Guepardo', 'Chimpancé', 'Pez Payaso',
       'Celacanto', 'Delfín Común', 'Sifaca de Coquerel', 'Perro Dálmata',
       'Cuón', 'Dingo', 'Dugongo', 'Gorila del Este', 'Equidna

Tarea de calse : Encontrar los osos cuya peso sea mayor a 100Kg

# Más de tablas

¿Cuál es la diferencia entre `select` y `column`, como nos podemos dar cuenta del tipo dato con lo que debemos trabajar?

Miremos la siguiente tabla analizando el número de atómico de algunos elementos químicos 

`El número atómico` es la cantidad de protones que se encuentran en el núcleo de un átomo de un elemento químico. 


```python
elementos = ["Hidrógeno", "Helio", "Litio", "Berilio", "Boro", "Carbono", "Nitrógeno", "Oxígeno", "Flúor", "Neón"]
numeros_atomicos = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


tabla_elementos = pd.DataFrame({
    "Elemento": elementos,
    "Número Atómico": numeros_atomicos
})
```
